import type { SchemaField, SchemaNode, SchemaRegistry } from '../schema/SchemaNode.js';
import { buildNameMap, propertyKey } from './identifiers.js';

/** Options for {@link generateTypeScript}. */
export interface CodegenOptions {
  /**
   * Import specifier for the runtime. Defaults to `'asn1-per-ts'`; point it at
   * a relative path when generating inside this repository.
   */
  importFrom?: string;
  /** Emit the `schemas` and `codecs` runtime values. Default `true`. */
  emitRuntime?: boolean;
  /** Name of the ASN.1 module, recorded in the file header. */
  moduleName?: string;
}

/** Which direction a type expression is being rendered for. */
type Mode = 'output' | 'input';

/**
 * Lets a nested structure be rendered as the name of the type it matches.
 *
 * The ASN.1 parser resolves type references by inlining them, so by the time a
 * schema reaches here every reference to `IssuingDetail` has been expanded into
 * its full structure and only genuine cycles remain as `$ref`. Emitting that
 * verbatim would defeat the point of generating named types, so structures are
 * matched back against the named schemas they came from.
 */
interface NamedShapes {
  /** Canonical form of a named schema to its TypeScript name. */
  byShape: Map<string, string>;
}

const INDENT = '  ';

/**
 * Generate a TypeScript module from a schema registry.
 *
 * Each ASN.1 type becomes a named `interface` (or `type` alias), which is what
 * makes generated schemas cheap for the compiler and readable in errors: the
 * names survive into hovers and diagnostics instead of expanding into
 * structural blobs.
 *
 * For each type `X` an `XInput` is also emitted — identical to `X` except that
 * DEFAULT fields may be omitted when encoding. Where the two coincide, `XInput`
 * is a plain alias.
 */
export function generateTypeScript(schemas: SchemaRegistry, options: CodegenOptions = {}): string {
  const { importFrom = 'asn1-per-ts', emitRuntime = true, moduleName } = options;

  const asnNames = Object.keys(schemas);
  const names = buildNameMap(asnNames, ['schemas', 'codecs']);
  const needsInput = computeNeedsInput(schemas);

  const usesBitString = asnNames.some(n => containsBitString(schemas[n], schemas, new Set()));
  const shapes = buildNamedShapes(schemas, names);

  const out: string[] = [];
  out.push('// Generated by asn1-per-ts. Do not edit by hand.');
  if (moduleName) out.push(`// ASN.1 module: ${moduleName}`);
  out.push('');

  const typeImports = ['SchemaRegistry', 'TypedCodec'];
  if (usesBitString) typeImports.push('BitStringValue');
  if (emitRuntime) out.push(`import { createCodecs } from '${importFrom}';`);
  out.push(`import type { ${typeImports.sort().join(', ')} } from '${importFrom}';`);
  out.push('');

  for (const asnName of asnNames) {
    const name = names.get(asnName)!;
    const node = schemas[asnName];

    out.push(...declare(name, node, 'output', names, shapes, asnName));
    out.push('');

    if (needsInput.get(asnName)) {
      out.push(...declare(`${name}Input`, node, 'input', names, shapes, asnName));
    } else {
      out.push(`/** Encoding input for {@link ${name}}; identical to it. */`);
      out.push(`export type ${name}Input = ${name};`);
    }
    out.push('');
  }

  if (emitRuntime) {
    out.push('/** The interchange schemas these types were generated from. */');
    out.push('export const schemas: SchemaRegistry = {');
    for (const asnName of asnNames) {
      out.push(`${INDENT}${propertyKey(asnName)}: ${literal(schemas[asnName], 1)},`);
    }
    out.push('};');
    out.push('');
    out.push('/** A typed codec per ASN.1 type, with `$ref` resolved across the module. */');
    out.push('export const codecs = createCodecs(schemas) as unknown as {');
    for (const asnName of asnNames) {
      const name = names.get(asnName)!;
      out.push(`${INDENT}${propertyKey(asnName)}: TypedCodec<${name}, ${name}Input>;`);
    }
    out.push('};');
    out.push('');
  }

  return out.join('\n');
}

/* -------------------------------------------------------------------------
 * Declarations
 * ---------------------------------------------------------------------- */

function declare(
  name: string,
  node: SchemaNode,
  mode: Mode,
  names: Map<string, string>,
  shapes: NamedShapes,
  asnName: string,
): string[] {
  const doc =
    mode === 'output'
      ? `/** ASN.1 \`${asnName}\`. */`
      : `/** Encoding input for {@link ${name.replace(/Input$/, '')}}: DEFAULT fields may be omitted. */`;

  if (node.type === 'SEQUENCE') {
    const body = sequenceMembers(node, mode, names, shapes, 1);
    if (body.length === 0) {
      return [doc, `export type ${name} = Record<never, never>;`];
    }
    return [doc, `export interface ${name} {`, ...body, '}'];
  }
  // Expand at the top level, or the declaration would alias itself.
  return [doc, `export type ${name} = ${tsType(node, mode, names, shapes, 0, true)};`];
}

function sequenceMembers(
  node: Extract<SchemaNode, { type: 'SEQUENCE' }>,
  mode: Mode,
  names: Map<string, string>,
  shapes: NamedShapes,
  depth: number,
): string[] {
  const pad = INDENT.repeat(depth);
  const lines: string[] = [];
  for (const field of node.fields) {
    const type = tsType(field.schema, mode, names, shapes, depth);
    lines.push(`${pad}${propertyKey(field.name)}${optionalMarker(field, mode)}: ${type};`);
  }
  for (const field of node.extensionFields ?? []) {
    const type = tsType(field.schema, mode, names, shapes, depth);
    lines.push(`${pad}${propertyKey(field.name)}?: ${type};`);
  }
  return lines;
}

/**
 * A DEFAULT field is always present after decoding — the decoder substitutes
 * the default — but may be omitted when encoding.
 */
function optionalMarker(field: SchemaField, mode: Mode): string {
  const hasDefault = field.defaultValue !== undefined;
  if (hasDefault) return mode === 'input' ? '?' : '';
  return field.optional ? '?' : '';
}

/* -------------------------------------------------------------------------
 * Type expressions
 * ---------------------------------------------------------------------- */

function tsType(
  node: SchemaNode,
  mode: Mode,
  names: Map<string, string>,
  shapes: NamedShapes,
  depth: number,
  expandNamed = false,
): string {
  if (!expandNamed) {
    const named = shapes.byShape.get(canonicalize(node));
    if (named !== undefined) return mode === 'input' ? `${named}Input` : named;
  }

  switch (node.type) {
    case 'BOOLEAN':
      return 'boolean';
    case 'NULL':
      return 'null';
    case 'INTEGER':
      return 'number';
    case 'ENUMERATED': {
      const values = [...node.values, ...(node.extensionValues ?? [])];
      return values.map(v => JSON.stringify(v)).join(' | ') || 'never';
    }
    case 'BIT STRING':
      return 'BitStringValue';
    case 'OCTET STRING':
      return 'Uint8Array';
    case 'OBJECT IDENTIFIER':
    case 'IA5String':
    case 'VisibleString':
    case 'UTF8String':
      return 'string';
    case 'SEQUENCE OF': {
      const item = tsType(node.item, mode, names, shapes, depth);
      return needsParens(item) ? `(${item})[]` : `${item}[]`;
    }
    case 'CHOICE': {
      const alts = [...node.alternatives, ...(node.extensionAlternatives ?? [])];
      if (alts.length === 0) return 'never';
      return alts
        .map(a => `{ key: ${JSON.stringify(a.name)}; value: ${tsType(a.schema, mode, names, shapes, depth)} }`)
        .join(' | ');
    }
    case 'SEQUENCE': {
      const members = sequenceMembers(node, mode, names, shapes, depth + 1);
      if (members.length === 0) return 'Record<never, never>';
      return `{\n${members.join('\n')}\n${INDENT.repeat(depth)}}`;
    }
    case '$ref': {
      const mapped = names.get(node.ref);
      if (!mapped) return 'unknown';
      return mode === 'input' ? `${mapped}Input` : mapped;
    }
    default:
      return 'unknown';
  }
}

/** A union or object type needs wrapping before `[]`. */
function needsParens(type: string): boolean {
  return type.includes('|') || type.startsWith('{');
}

/* -------------------------------------------------------------------------
 * Which types need a distinct Input variant
 * ---------------------------------------------------------------------- */

/**
 * A type needs its own `Input` shape when a DEFAULT field is reachable from it,
 * directly or through a `$ref`. Resolved as a fixpoint so reference cycles
 * terminate.
 */
function computeNeedsInput(schemas: SchemaRegistry): Map<string, boolean> {
  const direct = new Map<string, boolean>();
  const refs = new Map<string, Set<string>>();

  for (const [name, node] of Object.entries(schemas)) {
    const seen = new Set<string>();
    direct.set(name, hasDefault(node, seen));
    refs.set(name, seen);
  }

  const result = new Map(direct);
  let changed = true;
  while (changed) {
    changed = false;
    for (const [name, targets] of refs) {
      if (result.get(name)) continue;
      for (const target of targets) {
        if (result.get(target)) {
          result.set(name, true);
          changed = true;
          break;
        }
      }
    }
  }
  return result;
}

/** Walk one node, recording the `$ref` names it reaches. */
function hasDefault(node: SchemaNode, refsSeen: Set<string>): boolean {
  switch (node.type) {
    case 'SEQUENCE': {
      let found = false;
      for (const field of [...node.fields, ...(node.extensionFields ?? [])]) {
        if (field.defaultValue !== undefined) found = true;
        if (hasDefault(field.schema, refsSeen)) found = true;
      }
      return found;
    }
    case 'SEQUENCE OF':
      return hasDefault(node.item, refsSeen);
    case 'CHOICE': {
      let found = false;
      for (const alt of [...node.alternatives, ...(node.extensionAlternatives ?? [])]) {
        if (hasDefault(alt.schema, refsSeen)) found = true;
      }
      return found;
    }
    case '$ref':
      refsSeen.add(node.ref);
      return false;
    default:
      return false;
  }
}

function containsBitString(node: SchemaNode, schemas: SchemaRegistry, seen: Set<string>): boolean {
  switch (node.type) {
    case 'BIT STRING':
      return true;
    case 'SEQUENCE':
      return [...node.fields, ...(node.extensionFields ?? [])].some(f =>
        containsBitString(f.schema, schemas, seen),
      );
    case 'SEQUENCE OF':
      return containsBitString(node.item, schemas, seen);
    case 'CHOICE':
      return [...node.alternatives, ...(node.extensionAlternatives ?? [])].some(a =>
        containsBitString(a.schema, schemas, seen),
      );
    case '$ref': {
      if (seen.has(node.ref)) return false;
      seen.add(node.ref);
      const target = schemas[node.ref];
      return target ? containsBitString(target, schemas, seen) : false;
    }
    default:
      return false;
  }
}

/* -------------------------------------------------------------------------
 * Schema literal
 * ---------------------------------------------------------------------- */

/**
 * Render a SchemaNode as a TypeScript object literal. It is emitted under a
 * `SchemaRegistry` annotation, so the literal is contextually typed and the
 * compiler checks the generated schema is well-formed.
 */
function literal(value: unknown, depth: number): string {
  const pad = INDENT.repeat(depth);
  const inner = INDENT.repeat(depth + 1);

  if (value === null) return 'null';
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    const items = value.map(v => `${inner}${literal(v, depth + 1)}`);
    return `[\n${items.join(',\n')},\n${pad}]`;
  }
  if (typeof value === 'object') {
    const entries = Object.entries(value as Record<string, unknown>).filter(
      ([, v]) => v !== undefined,
    );
    if (entries.length === 0) return '{}';
    const items = entries.map(([k, v]) => `${inner}${propertyKey(k)}: ${literal(v, depth + 1)}`);
    return `{\n${items.join(',\n')},\n${pad}}`;
  }
  return JSON.stringify(value);
}

/* -------------------------------------------------------------------------
 * Matching inlined structures back to their named type
 * ---------------------------------------------------------------------- */

/** Composite types worth naming; primitives stay inline where they are used. */
const NAMEABLE = new Set(['SEQUENCE', 'CHOICE', 'SEQUENCE OF', 'ENUMERATED']);

function buildNamedShapes(schemas: SchemaRegistry, names: Map<string, string>): NamedShapes {
  const byShape = new Map<string, string>();
  for (const [asnName, node] of Object.entries(schemas)) {
    if (!NAMEABLE.has(node.type)) continue;
    const key = canonicalize(node);
    // First declaration wins, so structurally identical types resolve to one name.
    if (!byShape.has(key)) byShape.set(key, names.get(asnName)!);
  }
  return { byShape };
}

/** Key-order-independent structural key for a schema node. */
function canonicalize(value: unknown): string {
  if (value === null || typeof value !== 'object') return JSON.stringify(value) ?? 'null';
  if (Array.isArray(value)) return `[${value.map(canonicalize).join(',')}]`;
  const entries = Object.entries(value as Record<string, unknown>)
    .filter(([, v]) => v !== undefined)
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
  return `{${entries.map(([k, v]) => `${JSON.stringify(k)}:${canonicalize(v)}`).join(',')}}`;
}
